#!/usr/bin/env python3
"""Generate the phase-readout interpolation table and macros from plain JSON.

The three lambda values are trained by the same script.  Runs with the same
seed therefore share their initial weights, data split, batch order and
optimiser state.  Endpoint differences are reported as paired differences.
"""
import csv
import glob
import json
import os

import numpy as np


HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, 'results')
OUT = os.path.join(HERE, '..', 'manuscript', 'tables')
LAMBDAS = [(0.0, '0p0', 'Zero'), (0.5, '0p5', 'Half'), (1.0, '1p0', 'One')]
SEEDS = [0, 1, 2]


def fmt(x, nd=3):
    return ('{:.' + str(nd) + 'f}').format(float(x))


def mean_sd(vals):
    a = np.asarray(vals, dtype=float)
    return float(a.mean()), float(a.std(ddof=1)) if len(a) > 1 else 0.0


def pm(vals, nd=3, scale=1.0):
    m, s = mean_sd(vals)
    return '{} $\\pm$ {}'.format(fmt(scale * m, nd), fmt(scale * s, nd))


def load():
    rows = {}
    for lam, tag, _ in LAMBDAS:
        rr = []
        for seed in SEEDS:
            path = os.path.join(RESULTS, 'cnn_phase_lambda{}_g0.01_s{}.json'.format(tag, seed))
            if not os.path.isfile(path):
                raise SystemExit('PHASE_TABLE_FAIL: missing ' + path)
            d = json.load(open(path))
            if d.get('quick'):
                raise SystemExit('PHASE_TABLE_FAIL: quick record used: ' + path)
            if float(d['readout_lambda']) != lam or int(d['seed']) != seed:
                raise SystemExit('PHASE_TABLE_FAIL: metadata mismatch: ' + path)
            rr.append(d)
        rows[lam] = rr
    return rows


def main():
    rows = load()
    os.makedirs(OUT, exist_ok=True)
    csv_rows = []
    tex = os.path.join(OUT, 'phase_ablation_table.tex')
    with open(tex, 'w') as out:
        out.write('% generated by si_code/make_phase_ablation_table.py\n')
        out.write('\\begin{tabular}{@{}lcccccc@{}}\n\\toprule\n')
        out.write('$\\lambda$ & initial routed RMS & clean accuracy (\\%) & compactness & route defect & logit defect & prediction agreement \\\\\n\\midrule\n')
        for lam, _, _ in LAMBDAS:
            rr = rows[lam]
            initial_rms = [r['initial_routing_rms'] for r in rr]
            clean = [r['clean_test_acc'] for r in rr]
            compact = [r['cluster_compactness'] for r in rr]
            route = [r['routing_common_phase_relative_rms_deviation'] for r in rr]
            logit = [r['logit_common_phase_relative_rms_deviation'] for r in rr]
            agree = [r['prediction_agreement_under_common_phase'] for r in rr]
            cells = [fmt(lam, 1), pm(initial_rms, 4), pm(clean, 1, 100), pm(compact, 3),
                     pm(route, 4), pm(logit, 4), pm(agree, 3)]
            out.write(' & '.join(cells) + ' \\\\\n')
            csv_rows.append([lam, *mean_sd(initial_rms), *mean_sd(clean), *mean_sd(compact),
                             *mean_sd(route), *mean_sd(logit), *mean_sd(agree)])
        out.write('\\bottomrule\n\\end{tabular}\n')
    with open(os.path.join(OUT, 'phase_ablation_table.csv'), 'w', newline='') as out:
        w = csv.writer(out)
        w.writerow(['lambda', 'initial routed RMS mean', 'initial routed RMS sd',
                    'clean mean', 'clean sd', 'compactness mean', 'compactness sd',
                    'route relative RMS defect mean', 'route relative RMS defect sd',
                    'logit relative RMS defect mean', 'logit relative RMS defect sd',
                    'prediction agreement mean', 'prediction agreement sd'])
        w.writerows(csv_rows)

    macros = {'PhaseAblationSeeds': str(len(SEEDS))}
    for lam, _, name in LAMBDAS:
        rr = rows[lam]
        fields = [
            ('Clean', 'clean_test_acc', 1, 100),
            ('Compact', 'cluster_compactness', 3, 1),
            ('InitialRMS', 'initial_routing_rms', 4, 1),
            ('RouteDefect', 'routing_common_phase_relative_rms_deviation', 4, 1),
            ('LogitDefect', 'logit_common_phase_relative_rms_deviation', 4, 1),
            ('Agreement', 'prediction_agreement_under_common_phase', 3, 1),
        ]
        for suffix, key, nd, scale in fields:
            m, s = mean_sd([r[key] for r in rr])
            macros['Phase{}{}'.format(name, suffix)] = fmt(scale * m, nd)
            macros['Phase{}{}Sd'.format(name, suffix)] = fmt(scale * s, nd)
    paired = []
    half_minus_zero = []
    half_minus_one = []
    rms_spreads = []
    monotonic = 0
    for i, seed in enumerate(SEEDS):
        c0 = rows[0.0][i]['clean_test_acc']
        ch = rows[0.5][i]['clean_test_acc']
        c1 = rows[1.0][i]['clean_test_acc']
        paired.append(100 * (c1 - c0))
        half_minus_zero.append(100 * (ch - c0))
        half_minus_one.append(100 * (ch - c1))
        rms = [rows[lam][i]['initial_routing_rms'] for lam in (0.0, 0.5, 1.0)]
        rms_spreads.append(100 * (max(rms) / min(rms) - 1.0))
        monotonic += int(c0 < ch < c1)
    m, s = mean_sd(paired)
    macros['PhaseOneMinusZeroClean'] = fmt(m, 1)
    macros['PhaseOneMinusZeroCleanSd'] = fmt(s, 1)
    m, s = mean_sd(half_minus_zero)
    macros['PhaseHalfMinusZeroClean'] = fmt(m, 1)
    macros['PhaseHalfMinusZeroCleanSd'] = fmt(s, 1)
    m, s = mean_sd(half_minus_one)
    macros['PhaseHalfMinusOneClean'] = fmt(m, 1)
    macros['PhaseHalfMinusOneCleanSd'] = fmt(s, 1)
    macros['PhaseMaxInitialRMSSpreadPct'] = fmt(max(rms_spreads), 1)
    macros['PhaseEndpointPositiveSeeds'] = str(sum(x > 0 for x in paired))
    macros['PhaseMonotonicSeeds'] = str(monotonic)
    macros['PhaseAttributionStatus'] = 'supported' if all(x > 0 for x in paired) else 'not supported'
    with open(os.path.join(OUT, 'phase_ablation_numbers.tex'), 'w') as out:
        out.write('% generated by si_code/make_phase_ablation_table.py -- do not edit\n')
        for key, value in sorted(macros.items()):
            out.write('\\newcommand{\\%s}{%s}\n' % (key, value))
    print('PHASE_ABLATION_TABLE_OK: 9 records; paired lambda=1 minus lambda=0 =',
          macros['PhaseOneMinusZeroClean'], '+/-', macros['PhaseOneMinusZeroCleanSd'], 'points')


if __name__ == '__main__':
    main()
