#!/usr/bin/env python3
"""Generate the hierarchical-scale tables and manuscript macros from one JSON record.

The selected scale is the label-free choice already stored for each held-out seed.
Planted labels enter only the reported ARI and purity scores.  The fixed-k random
and oracle rows are controls, not alternative scale selectors.
"""
import argparse
import csv
import json
import os
from collections import Counter

import numpy as np


HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'manuscript', 'tables')


def values(rows, key):
    out = []
    for row in rows:
        val = row
        for part in key.split('/'):
            val = val.get(part) if isinstance(val, dict) else None
        if val is not None:
            out.append(float(val))
    return out


def ms(rows, key):
    vals = values(rows, key)
    return (float(np.mean(vals)) if vals else None,
            float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0,
            len(vals))


def fmt(x, nd=3):
    if x is None:
        return '--'
    return ('{:.' + str(nd) + 'f}').format(x)


def pm(rows, key, nd=3):
    mean, sd, _ = ms(rows, key)
    if mean is None:
        return '--'
    return '{} $\\pm$ {}'.format(fmt(mean, nd), fmt(sd, nd))


def selected_rows(runs, which):
    key = 'gauge_arm' if which == 'gauge' else 'matched_standard_arm'
    return [run['arms'][run['scale_selection'][key]] for run in runs]


def arm_rows(runs, arm):
    return [run['arms'][arm] for run in runs]


def paired_difference(runs, left, right):
    vals = [float(left(run)) - float(right(run)) for run in runs]
    return float(np.mean(vals)), float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0


def macro(macros, name, mean, sd=None, nd=3):
    macros[name] = fmt(mean, nd)
    if sd is not None:
        macros[name + 'Sd'] = fmt(sd, nd)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--tag', default='hierarchy_main')
    args = ap.parse_args()
    path = os.path.join(HERE, 'results', 'abm_{}.json'.format(args.tag))
    with open(path) as f:
        data = json.load(f)
    runs = data['runs']
    if not runs:
        raise SystemExit('HIERARCHY_TABLE_FAIL: no completed runs in ' + path)
    os.makedirs(OUT, exist_ok=True)

    level0 = [r['level0'] for r in runs]
    selected_g = selected_rows(runs, 'gauge')
    selected_s = selected_rows(runs, 'standard')
    frequency4 = arm_rows(runs, 'frequency_gauge_k4')
    standard4 = arm_rows(runs, 'frequency_standard_k4')
    random4 = arm_rows(runs, 'random_gauge_k4')
    oracle4 = arm_rows(runs, 'oracle_gauge_k4')
    selected_k = [int(r['scale_selection']['selected_k']) for r in runs]
    counts = Counter(selected_k)
    distribution = ', '.join('{}:{}'.format(k, counts[k]) for k in sorted(counts))

    rows = [
        ('Fine certified', 'level 0', level0, None, None),
        ('Selected gauge', 'selected', selected_g,
         'cycle_residual_abs_q95', 'candidate_units_certified_flat'),
        ('Selected control', 'same k', selected_s,
         'cycle_residual_abs_q95', 'candidate_units_certified_flat'),
        ('Frequency gauge', 'fixed k=4', frequency4,
         'cycle_residual_abs_q95', 'candidate_units_certified_flat'),
        ('Frequency control', 'fixed k=4', standard4,
         'cycle_residual_abs_q95', 'candidate_units_certified_flat'),
        ('Random gauge', 'fixed k=4', random4,
         'cycle_residual_abs_q95', 'candidate_units_certified_flat'),
        ('Label-oracle gauge', 'fixed k=4', oracle4,
         'cycle_residual_abs_q95', 'candidate_units_certified_flat'),
    ]
    csv_rows = []
    rendered_rows = []
    for label, scale, rr, qkey, ckey in rows:
        assigned = pm(rr, 'assigned_fraction', 3)
        modules = pm(rr, 'n_modules', 1)
        ari = pm(rr, 'ARI_vs_groups', 3)
        purity = pm(rr, 'purity', 3)
        q95 = pm(rr, qkey, 4) if qkey else '--'
        cert = pm(rr, ckey, 3) if ckey else '1.000'
        rendered_rows.append((label, scale, assigned, modules, ari, purity, q95, cert))
        csv_rows.append([label, scale, *ms(rr, 'assigned_fraction')[:2],
                         *ms(rr, 'n_modules')[:2], *ms(rr, 'ARI_vs_groups')[:2],
                         *ms(rr, 'purity')[:2],
                         *(ms(rr, qkey)[:2] if qkey else (None, None)),
                         *(ms(rr, ckey)[:2] if ckey else (1.0, 0.0))])
    tex_path = os.path.join(OUT, 'hierarchy_main_table.tex')
    with open(tex_path, 'w') as out:
        out.write('% generated by si_code/make_hierarchy_tables.py\n')
        out.write('\\begingroup\\scriptsize\\setlength{\\tabcolsep}{2.5pt}\n')
        out.write('\\textit{(a) Partition recovery}\\par\\smallskip\n')
        out.write('\\begin{tabularx}{\\textwidth}{@{}Xrrrr@{}}\n\\toprule\n')
        out.write('Construction & assigned & modules & ARI & purity \\\\\n\\midrule\n')
        for label, scale, assigned, modules, ari, purity, _, _ in rendered_rows:
            shown = '{} ({})'.format(label, scale)
            out.write('{} & {} & {} & {} & {} \\\\\n'.format(
                shown, assigned, modules, ari, purity))
        out.write('\\bottomrule\n\\end{tabularx}\n\\par\\medskip\n')
        out.write('\\textit{(b) Complete-cycle certification}\\par\\smallskip\n')
        out.write('\\begin{tabularx}{\\textwidth}{@{}Xrr@{}}\n\\toprule\n')
        out.write('Construction & cycle $q_{0.95}$ & certified \\\\\n\\midrule\n')
        for label, scale, _, _, _, _, q95, cert in rendered_rows:
            shown = '{} ({})'.format(label, scale)
            out.write('{} & {} & {} \\\\\n'.format(shown, q95, cert))
        out.write('\\bottomrule\n\\end{tabularx}\n\\endgroup\n')
    with open(os.path.join(OUT, 'hierarchy_main_table.csv'), 'w', newline='') as out:
        writer = csv.writer(out)
        writer.writerow(['construction', 'scale', 'assigned mean', 'assigned sd',
                         'modules mean', 'modules sd', 'ARI mean', 'ARI sd',
                         'purity mean', 'purity sd', 'cycle q95 mean', 'cycle q95 sd',
                         'certified fraction mean', 'certified fraction sd'])
        writer.writerows(csv_rows)

    sensitivity_rows = []
    with open(os.path.join(OUT, 'hierarchy_sensitivity_table.tex'), 'w') as out:
        out.write('% generated by si_code/make_hierarchy_tables.py\n')
        out.write('\\begin{tabular}{@{}llcccc@{}}\n\\toprule\n')
        out.write('$k$ & arm & ARI & purity & cycle $q_{0.95}$ & certified \\\\\n\\midrule\n')
        for k in data['params']['coarse_k_values']:
            for kind, label in [('gauge', 'gauge transporter'), ('standard', 'no transporter')]:
                rr = arm_rows(runs, 'frequency_{}_k{}'.format(kind, k))
                cells = [str(k), label, pm(rr, 'ARI_vs_groups', 3), pm(rr, 'purity', 3),
                         pm(rr, 'cycle_residual_abs_q95', 4),
                         pm(rr, 'candidate_units_certified_flat', 3)]
                out.write(' & '.join(cells) + ' \\\\\n')
                sensitivity_rows.append([k, kind, *ms(rr, 'ARI_vs_groups')[:2],
                                         *ms(rr, 'purity')[:2],
                                         *ms(rr, 'cycle_residual_abs_q95')[:2],
                                         *ms(rr, 'candidate_units_certified_flat')[:2]])
        out.write('\\bottomrule\n\\end{tabular}\n')
    with open(os.path.join(OUT, 'hierarchy_sensitivity_table.csv'), 'w', newline='') as out:
        writer = csv.writer(out)
        writer.writerow(['k', 'arm', 'ARI mean', 'ARI sd', 'purity mean', 'purity sd',
                         'cycle q95 mean', 'cycle q95 sd', 'certified mean', 'certified sd'])
        writer.writerows(sensitivity_rows)

    macros = {
        'HierarchySeeds': str(len(runs)),
        'HierarchySeedStart': str(min(r['seed'] for r in runs)),
        'HierarchySeedEnd': str(max(r['seed'] for r in runs)),
        'HierarchySelectedKDistribution': distribution,
        'HierarchySelectedKMode': str(counts.most_common(1)[0][0]),
        'HierarchySelectionSuccess': fmt(sum(k > 0 for k in selected_k) / len(selected_k), 2),
        'HierarchySelections': str(sum(k > 0 for k in selected_k)),
        'HierarchyAbstentions': str(sum(k == 0 for k in selected_k)),
    }
    named = [
        ('HierarchyLevelZeroARI', level0, 'ARI_vs_groups', 3),
        ('HierarchyLevelZeroPurity', level0, 'purity', 3),
        ('HierarchyLevelZeroModules', level0, 'n_modules', 1),
        ('HierarchyGaugeARI', selected_g, 'ARI_vs_groups', 3),
        ('HierarchyGaugePurity', selected_g, 'purity', 3),
        ('HierarchyGaugeModules', selected_g, 'n_modules', 1),
        ('HierarchyGaugeQ', selected_g, 'cycle_residual_abs_q95', 4),
        ('HierarchyGaugeCertified', selected_g, 'candidate_units_certified_flat', 3),
        ('HierarchyStandardARI', selected_s, 'ARI_vs_groups', 3),
        ('HierarchyStandardQ', selected_s, 'cycle_residual_abs_q95', 4),
        ('HierarchyStandardCertified', selected_s, 'candidate_units_certified_flat', 3),
        ('HierarchyFixedGaugeARI', frequency4, 'ARI_vs_groups', 3),
        ('HierarchyFixedGaugeQ', frequency4, 'cycle_residual_abs_q95', 4),
        ('HierarchyFixedGaugeCertified', frequency4, 'candidate_units_certified_flat', 3),
        ('HierarchyFixedStandardARI', standard4, 'ARI_vs_groups', 3),
        ('HierarchyFixedStandardQ', standard4, 'cycle_residual_abs_q95', 4),
        ('HierarchyFixedStandardCertified', standard4, 'candidate_units_certified_flat', 3),
        ('HierarchyRandomARI', random4, 'ARI_vs_groups', 3),
        ('HierarchyOracleARI', oracle4, 'ARI_vs_groups', 3),
    ]
    for name, rr, key, nd in named:
        mean, sd, _ = ms(rr, key)
        macro(macros, name, mean, sd, nd)
    dmean, dsd = paired_difference(
        runs,
        lambda r: r['scale_selection']['gauge_metrics']['ARI_vs_groups'],
        lambda r: r['level0']['ARI_vs_groups'])
    macro(macros, 'HierarchyGainOverLevelZero', dmean, dsd, 3)
    dmean, dsd = paired_difference(
        runs,
        lambda r: r['scale_selection']['gauge_metrics']['ARI_vs_groups'],
        lambda r: r['scale_selection']['matched_standard_metrics']['ARI_vs_groups'])
    macro(macros, 'HierarchyGainOverStandard', dmean, dsd, 3)
    for name, right in [
        ('HierarchyFixedGainOverLevelZero', lambda r: r['level0']['ARI_vs_groups']),
        ('HierarchyFixedGainOverStandard', lambda r: r['arms']['frequency_standard_k4']['ARI_vs_groups']),
        ('HierarchyFixedGainOverRandom', lambda r: r['arms']['random_gauge_k4']['ARI_vs_groups'])]:
        dmean, dsd = paired_difference(
            runs,
            lambda r: r['arms']['frequency_gauge_k4']['ARI_vs_groups'],
            right)
        macro(macros, name, dmean, dsd, 3)
    info = [r['scale_information'] for r in runs]
    for key, name in [
        ('frequency_affinity_same_group_mean', 'HierarchyFrequencyAffinitySame'),
        ('frequency_affinity_different_group_mean', 'HierarchyFrequencyAffinityDifferent'),
        ('temporal_affinity_same_group_mean', 'HierarchyTemporalAffinitySame'),
        ('temporal_affinity_different_group_mean', 'HierarchyTemporalAffinityDifferent')]:
        mean, sd, _ = ms(info, key)
        macro(macros, name, mean, sd, 3)
    control_path = os.path.join(HERE, 'results', 'hierarchy_controls.json')
    control = json.load(open(control_path)) if os.path.exists(control_path) else {}
    macros['HierarchyControls'] = 'PASS' if control.get('PASS') else 'FAIL'
    with open(os.path.join(OUT, 'hierarchy_numbers.tex'), 'w') as out:
        out.write('% generated by si_code/make_hierarchy_tables.py -- do not edit\n')
        for name, value in sorted(macros.items()):
            out.write('\\newcommand{\\%s}{%s}\n' % (name, value))
    print('HIERARCHY_TABLES_OK', path, len(runs), 'runs; selected k', distribution)


if __name__ == '__main__':
    main()
